FORMAT: 1A
HOST: http://service.tapioca.cbs.kz/api/v2

# Документация API v2

В данной ветке имеются слюдующие машрутизаторы:
 -  [tickets](http://service.tapioca.cbs.kz/api/v2/tickets/help)
 -  [parts](http://service.tapioca.cbs.kz/api/v2/parts/help)

## Не задокументированные API
 -  [ticket-history](http://service.tapioca.cbs.kz/api/v2/help)
 -  [comments](http://service.tapioca.cbs.kz/api/v2/help)
 -  [servie-type](http://service.tapioca.cbs.kz/api/v2/help)
