FORMAT: 1A
HOST: http://service.tapioca.cbs.kz/api/

# Документация API

Ниже представлена документация программного интерфейса по двум версиям:

 -  [api/v1](http://service.tapioca.cbs.kz/api/v1/help)
 -  [api/v2](http://service.tapioca.cbs.kz/api/v2/help)
 -  [api/help](http://service.tapioca.cbs.kz/api/help)
